---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: postsync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: postsync-job
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          env:
            - name: CIRCLECI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ct
                  key: CIRCLECI_TOKEN
          args:
            - |
              echo "Trigger Circleci Woerkflow"
              curl --request POST \
              --url https://circleci.com/api/v2/project/github/avinash-yamani-devops/circleci-test/pipeline \
              --header 'Circle-Token: $CIRCLECI_TOKEN' \
              --header 'content-type: application/json' \
              --data '{"parameters":{"run_workflow_test":true}}'
              
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: main
          image: nginx:latest
